from abc import abstractmethod
from datetime import datetime
from importlib.metadata.diagnose import inspect
from typing import Dict, Any, TypeVar

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Boolean,
)
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy.orm import mapped_column, object_mapper, MappedColumn
from sqlalchemy.orm.session import Session

from lib.core.models import TEntitySDKModel
from lib.infrastructure.repository.sqla.database import Base


class ModelBase(object):
    """
    Base class for all SQLA models.
    """

    __table_initialized__ = False

    @classmethod
    def from_dict(cls, data: dict):
        instance = cls()
        for key, value in data.items():
            if hasattr(instance, key):
                setattr(instance, key, value)
            elif value is not None:
                raise ValueError(f"Invalid field: {key}")
        return instance

    @abstractmethod
    def to_sdk_model(self) -> TEntitySDKModel:
        raise NotImplementedError("You must implement the to_sdk_model method in your model")

    @declared_attr  # type: ignore
    def __table_args__(cls: Base) -> tuple:  # type: ignore # pylint: disable=no-self-argument
        # pylint: disable=maybe-no-member
        return (
            CheckConstraint("CREATED_AT IS NOT NULL", name=cls.__tablename__.upper() + "_CREATED_NN"),
            CheckConstraint("UPDATED_AT IS NOT NULL", name=cls.__tablename__.upper() + "_UPDATED_NN"),
            {"mysql_engine": "InnoDB"},
        )

    @declared_attr
    def created_at(cls) -> MappedColumn[Any]:  # pylint: disable=no-self-argument
        return mapped_column("created_at", DateTime, default=datetime.utcnow)

    @declared_attr
    def updated_at(cls) -> MappedColumn[Any]:  # pylint: disable=no-self-argument
        return mapped_column("updated_at", DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def save(self, flush: bool = True, session: Session | None = None) -> None:
        """Save this object"""
        # Sessions created with autoflush=True be default since sqlAlchemy 1.4.
        # So explicatly calling session.flush is not necessary.
        # However, when autogenerated primary keys involved, calling
        # session.flush to get the id from DB.
        if not session:
            raise Exception("Session not found")

        session.add(self)
        if flush:
            session.flush()

    def delete(self, flush: bool = True, session: Session | None = None) -> None:
        """Delete this object"""
        if not session:
            raise Exception("Session not found")

        session.delete(self)
        if flush:
            session.flush()

    def update(self, values: dict[Any, Any], flush: bool = True, session: Session | None = None) -> None:
        """dict.update() behaviour."""
        if not session:
            raise Exception("Session not found")

        for k, v in values.items():
            self[k] = v
        if session and flush:
            session.flush()

    def __setitem__(self, key: Any, value: Any) -> None:
        setattr(self, key, value)

    def __getitem__(self, key: Any) -> Any:
        return getattr(self, key)

    def __iter__(self) -> "ModelBase":
        self._i = iter(object_mapper(self).columns)
        return self

    def __next__(self) -> tuple[str, Any]:
        n = next(self._i).name
        return n, getattr(self, n)

    def keys(self) -> list[str]:
        return list(self.__dict__.keys())

    def values(self) -> list[Any]:
        return list(self.__dict__.values())

    def items(self) -> list[tuple[str, Any]]:
        return list(self.__dict__.items())

    def to_dict(self) -> Dict[str, Any]:
        dictionary = self.__dict__.copy()
        dictionary.pop("_sa_instance_state")
        return dictionary

    next = __next__


class SoftModelBase(ModelBase):
    """
    Base class for SQLA Models with soft-deletion support
    """

    __table_initialized__ = False

    @declared_attr  # type: ignore
    def __table_args__(cls: Base) -> tuple:  # type: ignore
        # pylint: disable=no-self-argument
        # pylint: disable=maybe-no-member
        return (
            CheckConstraint("CREATED_AT IS NOT NULL", name=cls.__tablename__.upper() + "_CREATED_NN"),
            CheckConstraint("UPDATED_AT IS NOT NULL", name=cls.__tablename__.upper() + "_UPDATED_NN"),
            CheckConstraint("DELETED IS NOT NULL", name=cls.__tablename__.upper() + "_DELETED_NN"),
            {"mysql_engine": "InnoDB"},
        )

    @declared_attr
    def deleted(cls: Base) -> MappedColumn[Any]:  # pylint: disable=no-self-argument
        return mapped_column("deleted", Boolean, default=False)

    @declared_attr
    def deleted_at(cls: Base) -> MappedColumn[Any]:  # pylint: disable=no-self-argument
        return mapped_column("deleted_at", DateTime, nullable=True)

    def delete(self, flush: bool = True, session: Session | None = None) -> None:
        """Delete this object"""
        self.deleted = True  # TODO: typing: if session is None, it doesn't have delete
        self.deleted_at = datetime.utcnow()  # TODO: typing: if session is None, it doesn't have deleted_at
        self.save(session=session)  # TODO: typing: if session is None, it doesn't have save


TSoftModelBase = TypeVar("TSoftModelBase", bound=SoftModelBase)
